### ISSUE TITLE
Only works on api 21 and higher?

### ISSUE THREAD

**Issue by feliperoan** [steelkiwi/DotsLoaderView#1]
I have a project from the api 15, and I generate an error when compiling, this is because it only works on android 5.0 and +? or
`Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 15 cannot be smaller than version 21 declared in library [com.steelkiwi:dots-loader-view:1.0.0] D:\Work\meeting\meetingday-android\MeetingDayapp\app\build\intermediates\exploded-aar\com.steelkiwi\dots-loader-view\1.0.0\AndroidManifest.xml
	Suggestion: use tools:overrideLibrary="steelkiwi.com.library" to force usage`

**Comment by soulyaroslav** [comment]
@feliperoan Unfortunately, yes. It's works only 21+. Sorry I forgot to describe it in the README file
